### ISSUE TITLE
Feature: Ability to create additional custom configurable flyouts similar to Todo's

### ISSUE THREAD

**Issue by BrianGilbert** [ferdium/ferdium-app#104]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I play music via a Raspberry Pi running Plexamp, this is controllable via Plexamp's web interface.

I have currently added the interface as a custom website, however the interface isn't very well suited to fullscreen display.

I can think of multiple url's I would like to add in this way that aren't services that make sense to add in the left sidebar of Ferdium.

### Proposed Solution

It would be great if I could have additional site that operated as a flyout display like todo's do, with their own configurable hotkey to open and close.

### Alternatives Considered

Not really any other alternative

### Full screen width:

![Ferdium - Plexamp - Plexamp 2022-05-06 09-26-50](https://user-images.githubusercontent.com/114017/167043780-9c2b73c5-b30c-41c5-8b77-50964e8c52e2.png)

![Ferdium - Plexamp - Plexamp 2022-05-06 09-21-10](https://user-images.githubusercontent.com/114017/167043809-d6ed06f2-576c-40c5-84c7-d6d1391f2c31.png)

### Width constrained:

![Ferdium - Plexamp - Plexamp 2022-05-06 09-26-32](https://user-images.githubusercontent.com/114017/167043834-a7a8e6cb-69bb-479c-ba8a-a9c44198454e.png)

![Ferdium - Plexamp - Plexamp 2022-05-06 09-26-09](https://user-images.githubusercontent.com/114017/167043851-a0afa4e5-c0a6-4d94-a408-f72ac0f7aef0.png)
