### ISSUE TITLE
Need a way to fix the initial size of the Todo panel

### ISSUE THREAD

**Issue by heewonlee-nj** [ferdium/ferdium-app#1367]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/HEAD/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22enhancement+%3Asparkles%3A%22) for a feature request that matches the one I want to file, without success.

### Problem Description

I'm currently using Todoist a todo service, and the initial width of todo panel is too small, so I have to resize it every time I reload Ferdium.
It would be great if there was a way to fix the size of the Todo panel.

### Proposed Solution

Keep the size of the Todo panel resized by the user even after Ferdium restarts and reloads.

### Alternatives Considered

While a little less UX-friendly, there is also a way to allow the size of the initial Todo panel to be set in the appearance settings.

### Additional Information

This feature was mentioned in https://github.com/ferdium/ferdium-app/pull/1120#issuecomment-1599056279, but there doesn't appear to be any follow-up discussion, so we're creating a separate issue.

**Comment by RaphaelJenni** [comment]
I created a pull request for this.

(Team effort at #Hackergarten)
