### ISSUE TITLE
Feature: Capture todo server settings in .ferdium-data

### ISSUE THREAD

**Issue by BrianGilbert** [ferdium/ferdium-app#41]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I lost my customised Todo settings in transition from ferdi to ferdium, I use a website for my work time tracking instead of any of the built in options.

### Proposed Solution

capture user setting for Todo Server in .ferdium-data exports

### Alternatives Considered

not very user friendly option of just having to re-add it manually.
