### ISSUE TITLE
Feature: Autorefresh for ToDo

### ISSUE THREAD

**Issue by Latschenharry** [ferdium/ferdium-app#493]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-app/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When having a Todo Server like Nextcloud Tasks. The Tasks will not update untuil a force reload of the todo section. CTRL+Shift+Alt+R

### Proposed Solution

Maybe add a refreshtimer thats customisable to the todo settings.
![image](https://user-images.githubusercontent.com/12736979/179683975-9123ffeb-d94b-4412-906c-5a75c5fca5e3.png)

### Alternatives Considered

Add a hardcoded refresh timer.

**Comment by CorneliousJD** [comment]
I would also very much like to see this.
Similar use-case as you, using Nextcloud tasks, if I edit a task in my android app or something that doesn't show up on Ferdium unless I hard refresh it, or toggle to the to-do pane off entirely and back on (not just hiding it w/ the button, but disabling todo's and then re-enabling)
