### ISSUE TITLE
To Do for releasing Ferdium

### ISSUE THREAD

**Issue by m1karii** [ferdium/ferdium-app#9]
I expanded here on a list I found on discord on things that need to be done before initial release. if I missed something or added something unnecessary please let me know/ add it in comment

- [x] update name to "Ferdium" everywhere
- [x] update visual branding everywhere (logo, images in READMEs of app, recipes and server)
- [x] change copyright message everywhere to "Ferdium Contributors"
- [x] Setup the nightly build process
- [x] Setup the beta build process
- [x] Enable Snapstore login + publishing
- [ ] review licensing
- [x] add 'https://ferdium.org' to org repo description
- [x] temporarily make https://ferdium.org/download redirect to https://github.com/ferdium/ferdi/releases
- [x] get apple dev license and sign the macos builds
- [x] get windows dev license and sign the windows builds
- [x] host/run the API server
- [x] get the debug API server running
- [x] Initial setup is done. For the following (post 6.0.0 release) see #185
- [x] transferring pre-existing ferdi profile to ferdium:
   - [x] Migration scripts (#4)
   - [x] Further testing on migration scripts
- [x] replace `ferdi` with `ferdium` on all package managers
  - [x] homebrew (we ended up creating our own tap: https://github.com/ferdium/homebrew-ferdium )
  - [x] scoop
  - [x] chocolatey
  - [x] winget
  - [x] aur
  - [x] flatpak
- [x] documentation and FAQ ⇒ first FAQ on https://ferdium.org/faq
- [ ] *then* make an initial release - Ferdium 6.0
- [x] make https://ferdium.org/download redirect to https://github.com/ferdium/ferdium-app/releases (or just remove the old redirect) ⇒ custom page on the website
- [x] after the initial release: website
- [ ] Make recipes automatically update on the API server. https://github.com/ferdium/ferdium-server/issues/31 and https://github.com/ferdium/ferdium-server/issues/32
- [x] Find a solution for https://github.com/ferdium/ferdium-app/issues/224

**Comment by vraravam** [comment]
do we want to use GH Pages for the website content? That way, managing user/roles is easier, and I would think markdown is good enough for authoring content. I'm not sure if javascript is possible though

**Comment by nathanaelhoun** [comment]
I think GH Pages is enough for the website content, javascript is possible (raw javascript or with a bundling tool if really needed)

**Comment by Alpheron** [comment]
Visual branding of our entire organization should be completed, all the recipe, app, and server repositories have been modified to include our new logo.

**Comment by ftpd** [comment]
Is it possible for releasing just the client earlier for all the people like me, who wanted to use ferdi without any account somewhere? I really liked Ferdi and no 'alternatives' I've found are good enough.

**Comment by vraravam** [comment]
> Is it possible for releasing just the client earlier for all the people like me, who wanted to use ferdi without any account somewhere?

we are in the process of getting the rebranded (but unsigned) installables in place. Just need to find time to fix the GH publishing step. Once that's done, you should be able to download it from GH and use.

**Comment by dqos** [comment]
The website already uses GH Pages and it already setup. I have also checked the following:
- [x] add 'https://ferdium.org/' to org repo description
- [x] temporarily make https://ferdium.org/download redirect to https://github.com/ferdium/ferdi/releases

**Comment by alecive** [comment]
Do you have an ETA for what concerns beta releases? I'm not sure I want to risk using the nightlies...

**Comment by dqos** [comment]
> Do you have an ETA for what concerns beta releases? I'm not sure I want to risk using the nightlies...

Maybe @vraravam can tell more about that, but the nightlies have been stable enough for production, most of the community already use them 👍🏽

**Comment by vraravam** [comment]
> Maybe @vraravam can tell more about that,

We are already tracking the items for a beta/GA release in this ticket up above.

@dqos - the next item that we need to get will be the Apple Dev License.

**Comment by ftpd** [comment]
> > Do you have an ETA for what concerns beta releases? I'm not sure I want to risk using the nightlies...
> 
> Maybe @vraravam can tell more about that, but the nightlies have been stable enough for production, most of the community already use them 👍🏽

And where are these nighties? README.md points only to https://ferdium.org/download/, which doesn't work.

**Comment by vraravam** [comment]
https://github.com/ferdium/ferdium-app/releases

**Comment by ftpd** [comment]
Oh, silly me. When I've checked the main github page and seen [this](https://imgur.com/a/vmZ727q), I assumed there is no release, becaue 'normally' it shows something - but now I've just realized it's outsied the standard release, just a beta/nightly.

Sorry for stupid question and thanks for poinint me to it.

**Comment by alecive** [comment]
Oook, I guess I'll try the nightlies then :-) Thanks you all for the hard work!

**Comment by alecive** [comment]
I just downloaded the `exe` file and Avast on Windows is blocking it because of some threat. Do you mind sharing why? 

![image](https://user-images.githubusercontent.com/4378663/166252471-03b9bade-cfdf-4f14-b09c-5c9b2e62e4d1.png)

**Comment by dqos** [comment]
Because binaries are not signed yet. For support please join our Discord. This issue is for TODO tracking.

**Comment by SpecialAro** [comment]
> transferring pre-existing ferdi profile to ferdium (https://github.com/ferdium/ferdium-app/issues/4)

This could possibly be solved with https://github.com/ferdium/ferdium-server/pull/11 if someone was able to provide me help with authenticating and get data from Ferdi API.

**Comment by vraravam** [comment]
> This could possibly be solved with [ferdium/ferdium-server#11](https://github.com/ferdium/ferdium-server/pull/11) if someone was able to provide me help with authenticating and get data from Ferdi API.

But, why do we want to do this automatically? This would bring in a dependency that we cannot control (for eg if Amine decided to turn off the server or also change any API_KEY or something else that potentially breaks this implementation).

I would much rather have documented steps that the individual user can follow to export from Ferdi and then import into Ferdium.

**Comment by SpecialAro** [comment]
> > This could possibly be solved with [ferdium/ferdium-server#11](https://github.com/ferdium/ferdium-server/pull/11) if someone was able to provide me help with authenticating and get data from Ferdi API.
> 
> But, why do we want to do this automatically? This would bring in a dependency that we cannot control (for eg if Amine decided to turn off the server or also change any API_KEY or something else that potentially breaks this implementation).
> 
> I would much rather have documented steps that the individual user can follow to export from Ferdi and then import into Ferdium.

Ok, I see what you mean and I agree that the step forward is to document the export Ferdi + import Ferdium and maybe improve the migration scripts (?)

**Comment by vraravam** [comment]
> Ok, I see what you mean and I agree that the step forward is to document the export Ferdi + import Ferdium and maybe improve the migration scripts (?)

Yes, i think we are pretty good with the automated migration scripts at this point. We can always test more.

**Comment by vraravam** [comment]
Closing this ticket now that we have released v6.0.0
